### ISSUE TITLE
Memory Layers disappear from project if one is made permanent.

### ISSUE THREAD

**Issue by mikedufty** [YoannQDQ/qgis-memory-layer-saver#16] opened 2024-01-08 16:37 UTC
We have been having issues with memory layers sometimes losing all features when reopening saved projects.
I have now found a way to reproduce this.
It appears to be triggered by using the save scratch layer function (clicking on memory chip icon to right of layer in layer pane).
Tested by 
1 create blank project
2 add two temporary layers and add features to them.
3 use the save scratch layer function to convert one to a shape file.
4 save, close and reopen the project, the other scratch layer has lost it's features.  Display memory layer information shows 0 features.

Using 3.28.14 LTR and up to date memory layer plugin.
![image](https://github.com/YoannQDQ/qgis-memory-layer-saver/assets/34697905/5c12157f-f9b8-42da-8023-6e1d6973371f)

In other projects which have older memory layers imported from previous versions of the plugin, it appears the older memory layers may retain features.

**Comment by mikedufty** [comment] 2024-01-08 16:40
[Test.zip](https://github.com/YoannQDQ/qgis-memory-layer-saver/files/13863820/Test.zip)
Added example files
MLtest1.qgz has 3 memory layers.
MLtest2.qgz is the same file saved after 'save scratch layer' function used to convert the lake layer to shapefile.

**Comment by YoannQDQ** [comment] 2024-01-08 19:31
Great work, thanks. I don't have much time to work on that at the moment, but hopefully I'll be able to fix it by the end of the month

**Comment by YoannQDQ** [comment] 2024-01-27 22:50
Finaly had some time to fix this. Version 5.0.2 is waiting for approval.
#15 might be a duplicate of this issue, but I'm waiting for feedback on 5.0.2 before closing it.

**Closed by YoannQDQ** 2024-01-27 22:50 UTC
